<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cmsmssitedata [
 <!ELEMENT dtdversion (#PCDATA)>
 <!ELEMENT file (name,relto,(relfrom|embedded),content?)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT relto (#PCDATA)>
 <!ELEMENT relfrom (#PCDATA)>
 <!ELEMENT embedded (#PCDATA)>
 <!ELEMENT content (#PCDATA)>
 <!ELEMENT stylefiles (file*)>
 <!ELEMENT templatefiles (file*)>
 <!ELEMENT usertagfiles (file*)>
 <!ELEMENT themefiles (file*)>
 <!ELEMENT uploadfiles (file*)>
 <!ELEMENT stylegroups (stylegroup*)>
 <!ELEMENT stylegroup (id,name,description?)>
 <!ELEMENT id (#PCDATA)>
 <!ELEMENT description (#PCDATA)>
 <!ELEMENT stylesheets (stylesheet*)>
 <!ELEMENT stylesheet (id,originator,name,description?,media_type?,media_query?,owner_id?,type_id?,type_dflt?,listable?,contentfile?,content)>
 <!ELEMENT originator (#PCDATA)>
 <!ELEMENT media_type (#PCDATA)>
 <!ELEMENT media_query (#PCDATA)>
 <!ELEMENT owner_id (#PCDATA)>
 <!ELEMENT type_id (#PCDATA)>
 <!ELEMENT type_dflt (#PCDATA)>
 <!ELEMENT listable (#PCDATA)>
 <!ELEMENT contentfile (#PCDATA)>
 <!ELEMENT stylegroupmembers (stylegroupmember*)>
 <!ELEMENT stylegroupmember (group_id,css_id,item_order?)>
 <!ELEMENT group_id (#PCDATA)>
 <!ELEMENT css_id (#PCDATA)>
 <!ELEMENT item_order (#PCDATA)>
 <!ELEMENT templatetypes (tpltype*)>
 <!ELEMENT tpltype (id,originator,name,description?,lang_cb?,dflt_content_cb?,help_content_cb?,has_dflt?,requires_contentblocks?,one_only?,owner_id?,dflt_content?)>
 <!ELEMENT lang_cb (#PCDATA)>
 <!ELEMENT dflt_content_cb (#PCDATA)>
 <!ELEMENT help_content_cb (#PCDATA)>
 <!ELEMENT has_dflt (#PCDATA)>
 <!ELEMENT requires_contentblocks (#PCDATA)>
 <!ELEMENT one_only (#PCDATA)>
 <!ELEMENT dflt_content (#PCDATA)>
 <!ELEMENT templategroups (templategroup*)>
 <!ELEMENT templategroup (id,name,description?)>
 <!ELEMENT templates (template*)>
 <!ELEMENT template (id,originator,name,description?,hierarchy?,owner_id?,type_id?,type_dflt?,listable?,contentfile?,content)>
 <!ELEMENT hierarchy (#PCDATA)>
 <!ELEMENT templategroupmembers (templategroupmember*)>
 <!ELEMENT templategroupmember (group_id,tpl_id,item_order?)>
 <!ELEMENT tpl_id (#PCDATA)>
 <!ELEMENT pages (page*)>
 <!ELEMENT page (content_id,content_name,type,default_content?,show_in_menu?,active?,cachable?,secure?,owner_id,parent_id,template_id,item_order,menu_text?,content_alias?,metadata?,titleattribute?,page_url?,tabindex?,accesskey?,styles?)>
 <!ELEMENT content_id (#PCDATA)>
 <!ELEMENT content_name (#PCDATA)>
 <!ELEMENT type (#PCDATA)>
 <!ELEMENT default_content (#PCDATA)>
 <!ELEMENT show_in_menu (#PCDATA)>
 <!ELEMENT active (#PCDATA)>
 <!ELEMENT cacheable (#PCDATA)>
 <!ELEMENT secure (#PCDATA)>
 <!ELEMENT parent_id (#PCDATA)>
 <!ELEMENT template_id (#PCDATA)>
 <!ELEMENT menu_text (#PCDATA)>
 <!ELEMENT content_alias (#PCDATA)>
 <!ELEMENT metadata (#PCDATA)>
 <!ELEMENT titleattribute (#PCDATA)>
 <!ELEMENT page_url (#PCDATA)>
 <!ELEMENT tabindex (#PCDATA)>
 <!ELEMENT accesskey (#PCDATA)>
 <!ELEMENT styles (#PCDATA)>
 <!ELEMENT properties (property+)>
 <!ELEMENT property (content_id,prop_name,content)>
 <!ELEMENT prop_name (#PCDATA)>
 <!ELEMENT usertags (tag*)>
 <!ELEMENT tag (name,description?,parameters?,contentfile?,code)>
 <!ELEMENT parameters (#PCDATA)>
 <!ELEMENT code (#PCDATA)>
]>
<cmsmssitedata>
	<dtdversion>0.9</dtdversion>

	<stylegroups>
		<group>
			<id>2</id>
			<name>Steppo theme general-page styles</name>
			<description></description>
		</group>
		<group>
			<id>3</id>
			<name>Steppo theme home-page styles</name>
			<description>Includes news-display</description>
		</group>
		<group>
			<id>1</id>
			<name>Demonstration stylesheets group</name>
			<description>The stylesheets in this group will be applied in their specified order to each page which includes this group among its styles-sources.</description>
		</group>
	</stylegroups>
	<stylesheets>
		<stylesheet>
			<id>2</id>
			<originator>__CORE__</originator>
			<name>CSS grid</name>
			<description>Blueprint grid layout framework</description>
			<media_type>all</media_type>
			<media_query></media_query>
			<owner_id>1</owner_id>
			<type_id></type_id>
			<type_dflt>0</type_dflt>
			<listable>1</listable>
			<contentfile>0</contentfile>
			<content><![CDATA[/*! Blueprint v.3.1.1 2019 | https://blueprintcss.dev | MIT license */
html {
  box-sizing: border-box; }

*, *::before, *::after {
  box-sizing: inherit; }

[bp~=&apos;container&apos;] {
  width: 100%;
  margin: 0 auto;
  display: block;
  max-width: 1000px; }

[bp~=&apos;grid&apos;] {
  display: grid !important;
  grid-gap: 16px;
  grid-template-columns: repeat(12, 1fr); }

[bp~=&apos;vertical-start&apos;] {
  align-items: start; }

[bp~=&apos;vertical-center&apos;] {
  align-items: center; }

[bp~=&apos;vertical-end&apos;] {
  align-items: end; }

[bp~=&apos;between&apos;] {
  justify-content: center; }

[bp~=&apos;gap-none&apos;] {
  grid-gap: 0;
  margin-bottom: 0; }

[bp~=&apos;gap-column-none&apos;] {
  grid-column-gap: 0; }

[bp~=&apos;gap-row-none&apos;] {
  grid-row-gap: 0;
  margin-bottom: 0; }

[bp~=&apos;first&apos;] {
  order: -1; }

[bp~=&apos;last&apos;] {
  order: 12; }

[bp~=&apos;hide&apos;] {
  display: none !important; }

[bp~=&apos;show&apos;] {
  display: initial !important; }

[bp~=&apos;grid&apos;][bp*=&apos;@&apos;] {
  grid-template-columns: 12fr; }

[bp~=&apos;grid&apos;][bp*=&apos;@sm&apos;], [bp~=&apos;grid&apos;][bp*=&apos;@md&apos;], [bp~=&apos;grid&apos;][bp*=&apos;@lg&apos;], [bp~=&apos;grid&apos;][bp*=&apos;@xl&apos;] {
  grid-template-columns: 12fr; }

[bp~=&apos;1@sm&apos;], [bp~=&apos;1@md&apos;], [bp~=&apos;1@lg&apos;], [bp~=&apos;1@xl&apos;], [bp~=&apos;2@sm&apos;], [bp~=&apos;2@md&apos;], [bp~=&apos;2@lg&apos;], [bp~=&apos;2@xl&apos;], [bp~=&apos;3@sm&apos;], [bp~=&apos;3@md&apos;], [bp~=&apos;3@lg&apos;], [bp~=&apos;3@xl&apos;], [bp~=&apos;4@sm&apos;], [bp~=&apos;4@md&apos;], [bp~=&apos;4@lg&apos;], [bp~=&apos;4@xl&apos;], [bp~=&apos;5@sm&apos;], [bp~=&apos;5@md&apos;], [bp~=&apos;5@lg&apos;], [bp~=&apos;5@xl&apos;], [bp~=&apos;6@sm&apos;], [bp~=&apos;6@md&apos;], [bp~=&apos;6@lg&apos;], [bp~=&apos;6@xl&apos;], [bp~=&apos;7@sm&apos;], [bp~=&apos;7@md&apos;], [bp~=&apos;7@lg&apos;], [bp~=&apos;7@xl&apos;], [bp~=&apos;8@sm&apos;], [bp~=&apos;8@md&apos;], [bp~=&apos;8@lg&apos;], [bp~=&apos;8@xl&apos;], [bp~=&apos;9@sm&apos;], [bp~=&apos;9@md&apos;], [bp~=&apos;9@lg&apos;], [bp~=&apos;9@xl&apos;], [bp~=&apos;10@sm&apos;], [bp~=&apos;10@md&apos;], [bp~=&apos;10@lg&apos;], [bp~=&apos;10@xl&apos;], [bp~=&apos;11@sm&apos;], [bp~=&apos;11@md&apos;], [bp~=&apos;11@lg&apos;], [bp~=&apos;11@xl&apos;], [bp~=&apos;12@sm&apos;], [bp~=&apos;12@md&apos;], [bp~=&apos;12@lg&apos;], [bp~=&apos;12@xl&apos;] {
  grid-column: span 12; }

[bp~=&apos;grid&apos;][bp~=&apos;1&apos;] {
  grid-template-columns: repeat(12, 1fr); }

[bp~=&apos;1&apos;] {
  grid-column: span 1/span 1; }

[bp~=&apos;grid&apos;][bp~=&apos;2&apos;] {
  grid-template-columns: repeat(6, 1fr); }

[bp~=&apos;2&apos;] {
  grid-column: span 2/span 2; }

[bp~=&apos;grid&apos;][bp~=&apos;3&apos;] {
  grid-template-columns: repeat(4, 1fr); }

[bp~=&apos;3&apos;] {
  grid-column: span 3/span 3; }

[bp~=&apos;grid&apos;][bp~=&apos;4&apos;] {
  grid-template-columns: repeat(3, 1fr); }

[bp~=&apos;4&apos;] {
  grid-column: span 4/span 4; }

[bp~=&apos;grid&apos;][bp~=&apos;5&apos;] {
  grid-template-columns: repeat(2.4, 1fr); }

[bp~=&apos;5&apos;] {
  grid-column: span 5/span 5; }

[bp~=&apos;grid&apos;][bp~=&apos;6&apos;] {
  grid-template-columns: repeat(2, 1fr); }

[bp~=&apos;6&apos;] {
  grid-column: span 6/span 6; }

[bp~=&apos;grid&apos;][bp~=&apos;7&apos;] {
  grid-template-columns: repeat(1.71429, 1fr); }

[bp~=&apos;7&apos;] {
  grid-column: span 7/span 7; }

[bp~=&apos;grid&apos;][bp~=&apos;8&apos;] {
  grid-template-columns: repeat(1.5, 1fr); }

[bp~=&apos;8&apos;] {
  grid-column: span 8/span 8; }

[bp~=&apos;grid&apos;][bp~=&apos;9&apos;] {
  grid-template-columns: repeat(1.33333, 1fr); }

[bp~=&apos;9&apos;] {
  grid-column: span 9/span 9; }

[bp~=&apos;grid&apos;][bp~=&apos;10&apos;] {
  grid-template-columns: repeat(1.2, 1fr); }

[bp~=&apos;10&apos;] {
  grid-column: span 10/span 10; }

[bp~=&apos;grid&apos;][bp~=&apos;11&apos;] {
  grid-template-columns: repeat(1.09091, 1fr); }

[bp~=&apos;11&apos;] {
  grid-column: span 11/span 11; }

[bp~=&apos;grid&apos;][bp~=&apos;12&apos;] {
  grid-template-columns: repeat(1, 1fr); }

[bp~=&apos;12&apos;] {
  grid-column: span 12/span 12; }

[bp~=&apos;offset-1&apos;] {
  grid-column-start: 1; }

[bp~=&apos;offset-2&apos;] {
  grid-column-start: 2; }

[bp~=&apos;offset-3&apos;] {
  grid-column-start: 3; }

[bp~=&apos;offset-4&apos;] {
  grid-column-start: 4; }

[bp~=&apos;offset-5&apos;] {
  grid-column-start: 5; }

[bp~=&apos;offset-6&apos;] {
  grid-column-start: 6; }

[bp~=&apos;offset-7&apos;] {
  grid-column-start: 7; }

[bp~=&apos;offset-8&apos;] {
  grid-column-start: 8; }

[bp~=&apos;offset-9&apos;] {
  grid-column-start: 9; }

[bp~=&apos;offset-10&apos;] {
  grid-column-start: 10; }

[bp~=&apos;offset-11&apos;] {
  grid-column-start: 11; }

[bp~=&apos;offset-12&apos;] {
  grid-column-start: 12; }

@media (min-width: 480px) {
  [bp~=&apos;grid&apos;][bp~=&apos;1@sm&apos;] {
    grid-template-columns: repeat(12, 1fr); }
  [bp~=&apos;1@sm&apos;] {
    grid-column: span 1/span 1; }
  [bp~=&apos;grid&apos;][bp~=&apos;2@sm&apos;] {
    grid-template-columns: repeat(6, 1fr); }
  [bp~=&apos;2@sm&apos;] {
    grid-column: span 2/span 2; }
  [bp~=&apos;grid&apos;][bp~=&apos;3@sm&apos;] {
    grid-template-columns: repeat(4, 1fr); }
  [bp~=&apos;3@sm&apos;] {
    grid-column: span 3/span 3; }
  [bp~=&apos;grid&apos;][bp~=&apos;4@sm&apos;] {
    grid-template-columns: repeat(3, 1fr); }
  [bp~=&apos;4@sm&apos;] {
    grid-column: span 4/span 4; }
  [bp~=&apos;grid&apos;][bp~=&apos;5@sm&apos;] {
    grid-template-columns: repeat(2.4, 1fr); }
  [bp~=&apos;5@sm&apos;] {
    grid-column: span 5/span 5; }
  [bp~=&apos;grid&apos;][bp~=&apos;6@sm&apos;] {
    grid-template-columns: repeat(2, 1fr); }
  [bp~=&apos;6@sm&apos;] {
    grid-column: span 6/span 6; }
  [bp~=&apos;grid&apos;][bp~=&apos;7@sm&apos;] {
    grid-template-columns: repeat(1.71429, 1fr); }
  [bp~=&apos;7@sm&apos;] {
    grid-column: span 7/span 7; }
  [bp~=&apos;grid&apos;][bp~=&apos;8@sm&apos;] {
    grid-template-columns: repeat(1.5, 1fr); }
  [bp~=&apos;8@sm&apos;] {
    grid-column: span 8/span 8; }
  [bp~=&apos;grid&apos;][bp~=&apos;9@sm&apos;] {
    grid-template-columns: repeat(1.33333, 1fr); }
  [bp~=&apos;9@sm&apos;] {
    grid-column: span 9/span 9; }
  [bp~=&apos;grid&apos;][bp~=&apos;10@sm&apos;] {
    grid-template-columns: repeat(1.2, 1fr); }
  [bp~=&apos;10@sm&apos;] {
    grid-column: span 10/span 10; }
  [bp~=&apos;grid&apos;][bp~=&apos;11@sm&apos;] {
    grid-template-columns: repeat(1.09091, 1fr); }
  [bp~=&apos;11@sm&apos;] {
    grid-column: span 11/span 11; }
  [bp~=&apos;grid&apos;][bp~=&apos;12@sm&apos;] {
    grid-template-columns: repeat(1, 1fr); }
  [bp~=&apos;12@sm&apos;] {
    grid-column: span 12/span 12; }
  [bp~=&apos;offset-1@sm&apos;] {
    grid-column-start: 1; }
  [bp~=&apos;offset-2@sm&apos;] {
    grid-column-start: 2; }
  [bp~=&apos;offset-3@sm&apos;] {
    grid-column-start: 3; }
  [bp~=&apos;offset-4@sm&apos;] {
    grid-column-start: 4; }
  [bp~=&apos;offset-5@sm&apos;] {
    grid-column-start: 5; }
  [bp~=&apos;offset-6@sm&apos;] {
    grid-column-start: 6; }
  [bp~=&apos;offset-7@sm&apos;] {
    grid-column-start: 7; }
  [bp~=&apos;offset-8@sm&apos;] {
    grid-column-start: 8; }
  [bp~=&apos;offset-9@sm&apos;] {
    grid-column-start: 9; }
  [bp~=&apos;offset-10@sm&apos;] {
    grid-column-start: 10; }
  [bp~=&apos;offset-11@sm&apos;] {
    grid-column-start: 11; }
  [bp~=&apos;offset-12@sm&apos;] {
    grid-column-start: 12; }
  [bp~=&apos;hide@sm&apos;] {
    display: none !important; }
  [bp~=&apos;show@sm&apos;] {
    display: initial !important; }
  [bp~=&apos;first@sm&apos;] {
    order: -1; }
  [bp~=&apos;last@sm&apos;] {
    order: 12; } }

@media (min-width: 720px) {
  [bp~=&apos;grid&apos;][bp~=&apos;1@md&apos;] {
    grid-template-columns: repeat(12, 1fr); }
  [bp~=&apos;1@md&apos;] {
    grid-column: span 1/span 1; }
  [bp~=&apos;grid&apos;][bp~=&apos;2@md&apos;] {
    grid-template-columns: repeat(6, 1fr); }
  [bp~=&apos;2@md&apos;] {
    grid-column: span 2/span 2; }
  [bp~=&apos;grid&apos;][bp~=&apos;3@md&apos;] {
    grid-template-columns: repeat(4, 1fr); }
  [bp~=&apos;3@md&apos;] {
    grid-column: span 3/span 3; }
  [bp~=&apos;grid&apos;][bp~=&apos;4@md&apos;] {
    grid-template-columns: repeat(3, 1fr); }
  [bp~=&apos;4@md&apos;] {
    grid-column: span 4/span 4; }
  [bp~=&apos;grid&apos;][bp~=&apos;5@md&apos;] {
    grid-template-columns: repeat(2.4, 1fr); }
  [bp~=&apos;5@md&apos;] {
    grid-column: span 5/span 5; }
  [bp~=&apos;grid&apos;][bp~=&apos;6@md&apos;] {
    grid-template-columns: repeat(2, 1fr); }
  [bp~=&apos;6@md&apos;] {
    grid-column: span 6/span 6; }
  [bp~=&apos;grid&apos;][bp~=&apos;7@md&apos;] {
    grid-template-columns: repeat(1.71429, 1fr); }
  [bp~=&apos;7@md&apos;] {
    grid-column: span 7/span 7; }
  [bp~=&apos;grid&apos;][bp~=&apos;8@md&apos;] {
    grid-template-columns: repeat(1.5, 1fr); }
  [bp~=&apos;8@md&apos;] {
    grid-column: span 8/span 8; }
  [bp~=&apos;grid&apos;][bp~=&apos;9@md&apos;] {
    grid-template-columns: repeat(1.33333, 1fr); }
  [bp~=&apos;9@md&apos;] {
    grid-column: span 9/span 9; }
  [bp~=&apos;grid&apos;][bp~=&apos;10@md&apos;] {
    grid-template-columns: repeat(1.2, 1fr); }
  [bp~=&apos;10@md&apos;] {
    grid-column: span 10/span 10; }
  [bp~=&apos;grid&apos;][bp~=&apos;11@md&apos;] {
    grid-template-columns: repeat(1.09091, 1fr); }
  [bp~=&apos;11@md&apos;] {
    grid-column: span 11/span 11; }
  [bp~=&apos;grid&apos;][bp~=&apos;12@md&apos;] {
    grid-template-columns: repeat(1, 1fr); }
  [bp~=&apos;12@md&apos;] {
    grid-column: span 12/span 12; }
  [bp~=&apos;offset-1@md&apos;] {
    grid-column-start: 1; }
  [bp~=&apos;offset-2@md&apos;] {
    grid-column-start: 2; }
  [bp~=&apos;offset-3@md&apos;] {
    grid-column-start: 3; }
  [bp~=&apos;offset-4@md&apos;] {
    grid-column-start: 4; }
  [bp~=&apos;offset-5@md&apos;] {
    grid-column-start: 5; }
  [bp~=&apos;offset-6@md&apos;] {
    grid-column-start: 6; }
  [bp~=&apos;offset-7@md&apos;] {
    grid-column-start: 7; }
  [bp~=&apos;offset-8@md&apos;] {
    grid-column-start: 8; }
  [bp~=&apos;offset-9@md&apos;] {
    grid-column-start: 9; }
  [bp~=&apos;offset-10@md&apos;] {
    grid-column-start: 10; }
  [bp~=&apos;offset-11@md&apos;] {
    grid-column-start: 11; }
  [bp~=&apos;offset-12@md&apos;] {
    grid-column-start: 12; }
  [bp~=&apos;hide@md&apos;] {
    display: none !important; }
  [bp~=&apos;show@md&apos;] {
    display: initial !important; }
  [bp~=&apos;first@md&apos;] {
    order: -1; }
  [bp~=&apos;last@md&apos;] {
    order: 12; } }

@media (min-width: 960px) {
  [bp~=&apos;grid&apos;][bp~=&apos;1@lg&apos;] {
    grid-template-columns: repeat(12, 1fr); }
  [bp~=&apos;1@lg&apos;] {
    grid-column: span 1/span 1; }
  [bp~=&apos;grid&apos;][bp~=&apos;2@lg&apos;] {
    grid-template-columns: repeat(6, 1fr); }
  [bp~=&apos;2@lg&apos;] {
    grid-column: span 2/span 2; }
  [bp~=&apos;grid&apos;][bp~=&apos;3@lg&apos;] {
    grid-template-columns: repeat(4, 1fr); }
  [bp~=&apos;3@lg&apos;] {
    grid-column: span 3/span 3; }
  [bp~=&apos;grid&apos;][bp~=&apos;4@lg&apos;] {
    grid-template-columns: repeat(3, 1fr); }
  [bp~=&apos;4@lg&apos;] {
    grid-column: span 4/span 4; }
  [bp~=&apos;grid&apos;][bp~=&apos;5@lg&apos;] {
    grid-template-columns: repeat(2.4, 1fr); }
  [bp~=&apos;5@lg&apos;] {
    grid-column: span 5/span 5; }
  [bp~=&apos;grid&apos;][bp~=&apos;6@lg&apos;] {
    grid-template-columns: repeat(2, 1fr); }
  [bp~=&apos;6@lg&apos;] {
    grid-column: span 6/span 6; }
  [bp~=&apos;grid&apos;][bp~=&apos;7@lg&apos;] {
    grid-template-columns: repeat(1.71429, 1fr); }
  [bp~=&apos;7@lg&apos;] {
    grid-column: span 7/span 7; }
  [bp~=&apos;grid&apos;][bp~=&apos;8@lg&apos;] {
    grid-template-columns: repeat(1.5, 1fr); }
  [bp~=&apos;8@lg&apos;] {
    grid-column: span 8/span 8; }
  [bp~=&apos;grid&apos;][bp~=&apos;9@lg&apos;] {
    grid-template-columns: repeat(1.33333, 1fr); }
  [bp~=&apos;9@lg&apos;] {
    grid-column: span 9/span 9; }
  [bp~=&apos;grid&apos;][bp~=&apos;10@lg&apos;] {
    grid-template-columns: repeat(1.2, 1fr); }
  [bp~=&apos;10@lg&apos;] {
    grid-column: span 10/span 10; }
  [bp~=&apos;grid&apos;][bp~=&apos;11@lg&apos;] {
    grid-template-columns: repeat(1.09091, 1fr); }
  [bp~=&apos;11@lg&apos;] {
    grid-column: span 11/span 11; }
  [bp~=&apos;grid&apos;][bp~=&apos;12@lg&apos;] {
    grid-template-columns: repeat(1, 1fr); }
  [bp~=&apos;12@lg&apos;] {
    grid-column: span 12/span 12; }
  [bp~=&apos;offset-1@lg&apos;] {
    grid-column-start: 1; }
  [bp~=&apos;offset-2@lg&apos;] {
    grid-column-start: 2; }
  [bp~=&apos;offset-3@lg&apos;] {
    grid-column-start: 3; }
  [bp~=&apos;offset-4@lg&apos;] {
    grid-column-start: 4; }
  [bp~=&apos;offset-5@lg&apos;] {
    grid-column-start: 5; }
  [bp~=&apos;offset-6@lg&apos;] {
    grid-column-start: 6; }
  [bp~=&apos;offset-7@lg&apos;] {
    grid-column-start: 7; }
  [bp~=&apos;offset-8@lg&apos;] {
    grid-column-start: 8; }
  [bp~=&apos;offset-9@lg&apos;] {
    grid-column-start: 9; }
  [bp~=&apos;offset-10@lg&apos;] {
    grid-column-start: 10; }
  [bp~=&apos;offset-11@lg&apos;] {
    grid-column-start: 11; }
  [bp~=&apos;offset-12@lg&apos;] {
    grid-column-start: 12; }
  [bp~=&apos;hide@lg&apos;] {
    display: none !important; }
  [bp~=&apos;show@lg&apos;] {
    display: initial !important; }
  [bp~=&apos;first@lg&apos;] {
    order: -1; }
  [bp~=&apos;last@lg&apos;] {
    order: 12; } }

@media (min-width: 1440px) {
  [bp~=&apos;grid&apos;][bp~=&apos;1@xl&apos;] {
    grid-template-columns: repeat(12, 1fr); }
  [bp~=&apos;1@xl&apos;] {
    grid-column: span 1/span 1; }
  [bp~=&apos;grid&apos;][bp~=&apos;2@xl&apos;] {
    grid-template-columns: repeat(6, 1fr); }
  [bp~=&apos;2@xl&apos;] {
    grid-column: span 2/span 2; }
  [bp~=&apos;grid&apos;][bp~=&apos;3@xl&apos;] {
    grid-template-columns: repeat(4, 1fr); }
  [bp~=&apos;3@xl&apos;] {
    grid-column: span 3/span 3; }
  [bp~=&apos;grid&apos;][bp~=&apos;4@xl&apos;] {
    grid-template-columns: repeat(3, 1fr); }
  [bp~=&apos;4@xl&apos;] {
    grid-column: span 4/span 4; }
  [bp~=&apos;grid&apos;][bp~=&apos;5@xl&apos;] {
    grid-template-columns: repeat(2.4, 1fr); }
  [bp~=&apos;5@xl&apos;] {
    grid-column: span 5/span 5; }
  [bp~=&apos;grid&apos;][bp~=&apos;6@xl&apos;] {
    grid-template-columns: repeat(2, 1fr); }
  [bp~=&apos;6@xl&apos;] {
    grid-column: span 6/span 6; }
  [bp~=&apos;grid&apos;][bp~=&apos;7@xl&apos;] {
    grid-template-columns: repeat(1.71429, 1fr); }
  [bp~=&apos;7@xl&apos;] {
    grid-column: span 7/span 7; }
  [bp~=&apos;grid&apos;][bp~=&apos;8@xl&apos;] {
    grid-template-columns: repeat(1.5, 1fr); }
  [bp~=&apos;8@xl&apos;] {
    grid-column: span 8/span 8; }
  [bp~=&apos;grid&apos;][bp~=&apos;9@xl&apos;] {
    grid-template-columns: repeat(1.33333, 1fr); }
  [bp~=&apos;9@xl&apos;] {
    grid-column: span 9/span 9; }
  [bp~=&apos;grid&apos;][bp~=&apos;10@xl&apos;] {
    grid-template-columns: repeat(1.2, 1fr); }
  [bp~=&apos;10@xl&apos;] {
    grid-column: span 10/span 10; }
  [bp~=&apos;grid&apos;][bp~=&apos;11@xl&apos;] {
    grid-template-columns: repeat(1.09091, 1fr); }
  [bp~=&apos;11@xl&apos;] {
    grid-column: span 11/span 11; }
  [bp~=&apos;grid&apos;][bp~=&apos;12@xl&apos;] {
    grid-template-columns: repeat(1, 1fr); }
  [bp~=&apos;12@xl&apos;] {
    grid-column: span 12/span 12; }
  [bp~=&apos;offset-1@xl&apos;] {
    grid-column-start: 1; }
  [bp~=&apos;offset-2@xl&apos;] {
    grid-column-start: 2; }
  [bp~=&apos;offset-3@xl&apos;] {
    grid-column-start: 3; }
  [bp~=&apos;offset-4@xl&apos;] {
    grid-column-start: 4; }
  [bp~=&apos;offset-5@xl&apos;] {
    grid-column-start: 5; }
  [bp~=&apos;offset-6@xl&apos;] {
    grid-column-start: 6; }
  [bp~=&apos;offset-7@xl&apos;] {
    grid-column-start: 7; }
  [bp~=&apos;offset-8@xl&apos;] {
    grid-column-start: 8; }
  [bp~=&apos;offset-9@xl&apos;] {
    grid-column-start: 9; }
  [bp~=&apos;offset-10@xl&apos;] {
    grid-column-start: 10; }
  [bp~=&apos;offset-11@xl&apos;] {
    grid-column-start: 11; }
  [bp~=&apos;offset-12@xl&apos;] {
    grid-column-start: 12; }
  [bp~=&apos;hide@xl&apos;] {
    display: none !important; }
  [bp~=&apos;show@xl&apos;] {
    display: initial !important; }
  [bp~=&apos;first@xl&apos;] {
    order: -1; }
  [bp~=&apos;last@xl&apos;] {
    order: 12; } }

[bp~=&apos;flex&apos;] {
  flex-wrap: wrap;
  display: flex; }

[bp~=&apos;fill&apos;] {
  flex: 1 1 0%;
  flex-basis: 0%; }

[bp~=&apos;fit&apos;] {
  flex-basis: auto; }

[bp~=&apos;float-center&apos;] {
  margin-left: auto;
  margin-right: auto;
  display: block;
  float: none; }

[bp~=&apos;float-left&apos;] {
  float: left; }

[bp~=&apos;float-right&apos;] {
  float: right; }

[bp~=&apos;clear-fix&apos;]::after {
  content: &apos;&apos;;
  display: table;
  clear: both; }

[bp~=&apos;text-left&apos;] {
  text-align: left; }

[bp~=&apos;text-right&apos;] {
  text-align: right; }

[bp~=&apos;text-center&apos;] {
  text-align: center; }

[bp~=&apos;1--max&apos;] {
  max-width: 83.33333px !important; }

[bp~=&apos;2--max&apos;] {
  max-width: 166.66667px !important; }

[bp~=&apos;3--max&apos;] {
  max-width: 250px !important; }

[bp~=&apos;4--max&apos;] {
  max-width: 333.33333px !important; }

[bp~=&apos;5--max&apos;] {
  max-width: 416.66667px !important; }

[bp~=&apos;6--max&apos;] {
  max-width: 500px !important; }

[bp~=&apos;7--max&apos;] {
  max-width: 583.33333px !important; }

[bp~=&apos;8--max&apos;] {
  max-width: 666.66667px !important; }

[bp~=&apos;9--max&apos;] {
  max-width: 750px !important; }

[bp~=&apos;10--max&apos;] {
  max-width: 833.33333px !important; }

[bp~=&apos;11--max&apos;] {
  max-width: 916.66667px !important; }

[bp~=&apos;12--max&apos;] {
  max-width: 1000px !important; }

[bp~=&apos;full-width&apos;] {
  width: 100%; }

@media (max-width: 480px) {
  [bp~=&apos;full-width-until@sm&apos;] {
    width: 100% !important;
    max-width: 100% !important; } }

@media (max-width: 720px) {
  [bp~=&apos;full-width-until@md&apos;] {
    width: 100% !important;
    max-width: 100% !important; } }

@media (max-width: 960px) {
  [bp~=&apos;full-width-until@lg&apos;] {
    width: 100% !important;
    max-width: 100% !important; } }

@media (max-width: 1440px) {
  [bp~=&apos;full-width-until@xl&apos;] {
    width: 100% !important;
    max-width: 100% !important; } }

[bp~=&apos;margin--xs&apos;] {
  margin: 4px !important; }

[bp~=&apos;margin-top--xs&apos;] {
  margin-top: 4px !important; }

[bp~=&apos;margin-bottom--xs&apos;] {
  margin-bottom: 4px !important; }

[bp~=&apos;margin-right--xs&apos;] {
  margin-right: 4px !important; }

[bp~=&apos;margin-left--xs&apos;] {
  margin-left: 4px !important; }

[bp~=&apos;padding--xs&apos;] {
  padding: 4px !important; }

[bp~=&apos;padding-top--xs&apos;] {
  padding-top: 4px !important; }

[bp~=&apos;padding-bottom--xs&apos;] {
  padding-bottom: 4px !important; }

[bp~=&apos;padding-right--xs&apos;] {
  padding-right: 4px !important; }

[bp~=&apos;padding-left--xs&apos;] {
  padding-left: 4px !important; }

[bp~=&apos;margin--sm&apos;] {
  margin: 8px !important; }

[bp~=&apos;margin-top--sm&apos;] {
  margin-top: 8px !important; }

[bp~=&apos;margin-bottom--sm&apos;] {
  margin-bottom: 8px !important; }

[bp~=&apos;margin-right--sm&apos;] {
  margin-right: 8px !important; }

[bp~=&apos;margin-left--sm&apos;] {
  margin-left: 8px !important; }

[bp~=&apos;padding--sm&apos;] {
  padding: 8px !important; }

[bp~=&apos;padding-top--sm&apos;] {
  padding-top: 8px !important; }

[bp~=&apos;padding-bottom--sm&apos;] {
  padding-bottom: 8px !important; }

[bp~=&apos;padding-right--sm&apos;] {
  padding-right: 8px !important; }

[bp~=&apos;padding-left--sm&apos;] {
  padding-left: 8px !important; }

[bp~=&apos;margin&apos;] {
  margin: 16px !important; }

[bp~=&apos;margin-top&apos;] {
  margin-top: 16px !important; }

[bp~=&apos;margin-bottom&apos;] {
  margin-bottom: 16px !important; }

[bp~=&apos;margin-right&apos;] {
  margin-right: 16px !important; }

[bp~=&apos;margin-left&apos;] {
  margin-left: 16px !important; }

[bp~=&apos;padding&apos;] {
  padding: 16px !important; }

[bp~=&apos;padding-top&apos;] {
  padding-top: 16px !important; }

[bp~=&apos;padding-bottom&apos;] {
  padding-bottom: 16px !important; }

[bp~=&apos;padding-right&apos;] {
  padding-right: 16px !important; }

[bp~=&apos;padding-left&apos;] {
  padding-left: 16px !important; }

[bp~=&apos;margin--lg&apos;] {
  margin: 24px !important; }

[bp~=&apos;margin-top--lg&apos;] {
  margin-top: 24px !important; }

[bp~=&apos;margin-bottom--lg&apos;] {
  margin-bottom: 24px !important; }

[bp~=&apos;margin-right--lg&apos;] {
  margin-right: 24px !important; }

[bp~=&apos;margin-left--lg&apos;] {
  margin-left: 24px !important; }

[bp~=&apos;padding--lg&apos;] {
  padding: 24px !important; }

[bp~=&apos;padding-top--lg&apos;] {
  padding-top: 24px !important; }

[bp~=&apos;padding-bottom--lg&apos;] {
  padding-bottom: 24px !important; }

[bp~=&apos;padding-right--lg&apos;] {
  padding-right: 24px !important; }

[bp~=&apos;padding-left--lg&apos;] {
  padding-left: 24px !important; }

[bp~=&apos;margin--none&apos;] {
  margin: 0 !important; }

[bp~=&apos;margin-top--none&apos;] {
  margin-top: 0 !important; }

[bp~=&apos;margin-bottom--none&apos;] {
  margin-bottom: 0 !important; }

[bp~=&apos;margin-right--none&apos;] {
  margin-right: 0 !important; }

[bp~=&apos;margin-left--none&apos;] {
  margin-left: 0 !important; }

[bp~=&apos;padding--none&apos;] {
  padding: 0 !important; }

[bp~=&apos;padding-top--none&apos;] {
  padding-top: 0 !important; }

[bp~=&apos;padding-bottom--none&apos;] {
  padding-bottom: 0 !important; }

[bp~=&apos;padding-right--none&apos;] {
  padding-right: 0 !important; }

[bp~=&apos;padding-left--none&apos;] {
  padding-left: 0 !important; }
]]></content>
		</stylesheet>
		<stylesheet>
			<id>3</id>
			<originator>__CORE__</originator>
			<name>Flexbox grid</name>
			<description>Flex Grid Lite layout framework</description>
			<media_type>all</media_type>
			<media_query></media_query>
			<owner_id>1</owner_id>
			<type_id></type_id>
			<type_dflt>0</type_dflt>
			<listable>1</listable>
			<contentfile>0</contentfile>
			<content><![CDATA[/*! Flex Grid Lite v.2.0 | Copyright (C) 2017-2021 Elliot Dahl | MIT license */
.cell {
	box-sizing: border-box;
	margin: 4px 4px;
	padding: 0;
	max-width: 100%;
	min-width: 0;
	-webkit-box: 1;
	-moz-box: 1;
	-webkit-flex: 1 0 0;
	-ms-flex: 1 0 0;
	flex: 1 0 0;
}

.cell.align_top {
	-webkit-align-self: flex-start;
	-ms-flex-item-align: start;
	align-self: flex-start;
}

.cell.align_bottom {
	-webkit-align-self: flex-end;
	-ms-flex-item-align: end;
	align-self: flex-end;
}

.cell.align_middle {
	-webkit-align-self: center;
	-ms-flex-item-align: center;
	align-self: center;
}

.cell.content_top {
	display: -webkit-box;
	display: -moz-box;
	display: -webkit-flex;
	display: -ms-flexbox;
	display: flex;
	-ms-box-direction: normal;
	-ms-box-orient: vertical;
	-webkit-box-direction: normal;
	-webkit-box-orient: vertical;
	-moz-box-direction: normal;
	-moz-box-orient: vertical;
	-webkit-flex-direction: column;
	-ms-flex-direction: column;
	flex-direction: column;
	-ms-box-pack: start;
	-webkit-box-pack: start;
	-moz-box-pack: start;
	-ms-flex-pack: start;
	-webkit-justify-content: flex-start;
	justify-content: flex-start;
}

.cell.content_bottom {
	display: -webkit-box;
	display: -moz-box;
	display: -webkit-flex;
	display: -ms-flexbox;
	display: flex;
	-ms-box-direction: normal;
	-ms-box-orient: vertical;
	-webkit-box-direction: normal;
	-webkit-box-orient: vertical;
	-moz-box-direction: normal;
	-moz-box-orient: vertical;
	-webkit-flex-direction: column;
	-ms-flex-direction: column;
	flex-direction: column;
	-ms-box-pack: end;
	-webkit-box-pack: end;
	-moz-box-pack: end;
	-ms-flex-pack: end;
	-webkit-justify-content: flex-end;
	justify-content: flex-end;
}

.cell.content_middle {
	display: -webkit-box;
	display: -moz-box;
	display: -webkit-flex;
	display: -ms-flexbox;
	display: flex;
	-ms-box-direction: normal;
	-ms-box-orient: vertical;
	-webkit-box-direction: normal;
	-webkit-box-orient: vertical;
	-moz-box-direction: normal;
	-moz-box-orient: vertical;
	-webkit-flex-direction: column;
	-ms-flex-direction: column;
	flex-direction: column;
	-ms-box-pack: center;
	-webkit-box-pack: center;
	-moz-box-pack: center;
	-ms-flex-pack: center;
	-webkit-justify-content: center;
	justify-content: center;
}

.cell.first {
	-ms-box-ordinal-group: -9;
	-webkit-box-ordinal-group: -9;
	-moz-box-ordinal-group: -9;
	-webkit-order: -10;
	-ms-flex-order: -10;
	order: -10;
}

.cell.last {
	-ms-box-ordinal-group: 23;
	-webkit-box-ordinal-group: 23;
	-moz-box-ordinal-group: 23;
	-webkit-order: 22;
	-ms-flex-order: 22;
	order: 22;
}

.cell.fixed {
	-webkit-box: initial;
	-moz-box: initial;
	-webkit-flex: none;
	-ms-flex: none;
	flex: none;
}

.cell.col-1 {
	-ms-flex-preferred-size: 8.33333%;
	-webkit-flex-basis: 8.33333%;
	flex-basis: 8.33333%;
	max-width: 8.33333%;
}

.cell.col-2 {
	-ms-flex-preferred-size: 16.66667%;
	-webkit-flex-basis: 16.66667%;
	flex-basis: 16.66667%;
	max-width: 16.66667%;
}

.cell.col-3 {
	-ms-flex-preferred-size: 25%;
	-webkit-flex-basis: 25%;
	flex-basis: 25%;
	max-width: 25%;
}

.cell.col-4 {
	-ms-flex-preferred-size: 33.33333%;
	-webkit-flex-basis: 33.33333%;
	flex-basis: 33.33333%;
	max-width: 33.33333%;
}

.cell.col-5 {
	-ms-flex-preferred-size: 41.66667%;
	-webkit-flex-basis: 41.66667%;
	flex-basis: 41.66667%;
	max-width: 41.66667%;
}

.cell.col-6 {
	-ms-flex-preferred-size: 50%;