<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cmsmsinstall [
 <!ELEMENT dtdversion (#PCDATA)>
 <!ELEMENT templatetypes (tpltype*)>
 <!ELEMENT tpltype (id,originator,name,description?,lang_cb?,dflt_content_cb?,help_content_cb?,has_dflt?,requires_contentblocks?,one_only?,owner_id?,dflt_content?)>
 <!ELEMENT id (#PCDATA)>
 <!ELEMENT originator (#PCDATA)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT description (#PCDATA)>
 <!ELEMENT lang_cb (#PCDATA)>
 <!ELEMENT dflt_content_cb (#PCDATA)>
 <!ELEMENT help_content_cb (#PCDATA)>
 <!ELEMENT has_dflt (#PCDATA)>
 <!ELEMENT requires_contentblocks (#PCDATA)>
 <!ELEMENT one_only (#PCDATA)>
 <!ELEMENT owner_id (#PCDATA)>
 <!ELEMENT dflt_content (#PCDATA)>
 <!ELEMENT templates (template*)>
 <!ELEMENT template (id,originator,name,description?,hierarchy?,owner_id?,type_id?,type_dflt?,listable?,contentfile?,content)>
 <!ELEMENT hierarchy (#PCDATA)>
 <!ELEMENT type_id (#PCDATA)>
 <!ELEMENT type_dflt (#PCDATA)>
 <!ELEMENT listable (#PCDATA)>
 <!ELEMENT contentfile (#PCDATA)>
 <!ELEMENT content (#PCDATA)>
 <!ELEMENT pages (page*)>
 <!ELEMENT page (content_id,content_name,type,default_content?,show_in_menu?,active?,cachable?,secure?,owner_id,parent_id,template_id,item_order,menu_text?,content_alias?,metadata?,titleattribute?,page_url?,tabindex?,accesskey?,styles?)>
 <!ELEMENT content_id (#PCDATA)>
 <!ELEMENT content_name (#PCDATA)>
 <!ELEMENT type (#PCDATA)>
 <!ELEMENT default_content (#PCDATA)>
 <!ELEMENT show_in_menu (#PCDATA)>
 <!ELEMENT active (#PCDATA)>
 <!ELEMENT cacheable (#PCDATA)>
 <!ELEMENT parent_id (#PCDATA)>
 <!ELEMENT template_id (#PCDATA)>
 <!ELEMENT menu_text (#PCDATA)>
 <!ELEMENT content_alias (#PCDATA)>
 <!ELEMENT metadata (#PCDATA)>
 <!ELEMENT titleattribute (#PCDATA)>
 <!ELEMENT page_url (#PCDATA)>
 <!ELEMENT tabindex (#PCDATA)>
 <!ELEMENT accesskey (#PCDATA)>
 <!ELEMENT styles (#PCDATA)>
 <!ELEMENT properties (property+)>
 <!ELEMENT property (content_id,prop_name,content)>
 <!ELEMENT prop_name (#PCDATA)>
]>
<cmsmsinstall>
	<dtdversion>0.9</dtdversion>
	<templatetypes>
		<tpltype>
			<id>1</id>
			<name>page</name>
			<originator>__CORE__</originator>
			<lang_cb>CMSMS\internal\std_layout_template_callbacks::page_type_lang_callback</lang_cb>
			<dflt_content_cb>CMSMS\internal\std_layout_template_callbacks::reset_page_type_defaults</dflt_content_cb>
			<help_content_cb>CMSMS\internal\std_layout_template_callbacks::template_help_callback</help_content_cb>
			<one_only>1</one_only>
			<owner_id>1</owner_id>
		</tpltype>
		<tpltype>
			<id>2</id>
			<name>generic</name>
			<originator>__CORE__</originator>
			<lang_cb>CMSMS\internal\std_layout_template_callbacks::generic_type_lang_callback</lang_cb>
			<dflt_content_cb></dflt_content_cb>
			<help_content_cb>CMSMS\internal\std_layout_template_callbacks::template_help_callback</help_content_cb>
			<one_only>1</one_only>
			<owner_id>1</owner_id>
		</tpltype>
	</templatetypes>
	<templates>
		<template>
			<id>1</id>
			<name>Default</name>
			<description>A simple starting point to build templates from</description>
			<type_id>1</type_id>
			<type_dflt>1</type_dflt>
			<owner_id>1</owner_id>
			<listable>1</listable>
			<contentfile>0</contentfile>
			<content><![CDATA[{strip} {process_pagedata} {/strip}
&lt;!doctype html&gt;
&lt;html lang=&quot;{cms_get_language}&quot;&gt;
&lt;head&gt;
  &lt;title&gt;{title} - {sitename}&lt;/title&gt;
  {metadata}
  {cms_stylesheet}
&lt;/head&gt;
&lt;body&gt;
  &lt;header id=&quot;header&quot;&gt;
    &lt;h1&gt;{sitename}&lt;/h1&gt;
  &lt;/header&gt;

  &lt;nav id=&quot;menu&quot;&gt;
    {Navigator}
  &lt;/nav&gt;

  &lt;section id=&quot;content&quot;&gt;
    &lt;h1&gt;{title}&lt;/h1&gt;
    {content}
  &lt;/section&gt;
&lt;/body&gt;
&lt;/html&gt;]]></content>
		</template>
	</templates>
	<pages>
		<page>
			<content_id>1</content_id>
			<content_name>Home</content_name>
			<content_alias>home</content_alias>
			<type>content</type>
			<template_id>1</template_id>
			<parent_id>-1</parent_id>
			<active>1</active>
			<default_content>1</default_content>
			<show_in_menu>0</show_in_menu>
			<cachable>1</cachable>
		</page>
	</pages>
	<properties>
		<property>
			<content_id>1</content_id>
			<prop_name>searchable</prop_name>
			<content><![CDATA[1]]></content>
		</property>
		<property>
			<content_id>1</content_id>
			<prop_name>content_en</prop_name>
			<content><![CDATA[&lt;p&gt;This is a minimal but fully functional installation of CMS Made Simple.&lt;/p&gt;&lt;p&gt;To get to the site&apos;s Administration Console, log in as the administrator (with the username/password supplied during the installation process) at http://yourwebsite.com/cmsmspath/admin. If this is your site click &lt;a title=&quot;CMSMS Demo Admin Panel&quot; href=&quot;admin&quot;&gt;here&lt;/a&gt; to log in.&lt;/p&gt;&lt;p&gt;Read about how to use CMS Made Simple in the &lt;a class=&quot;external&quot; href=&quot;http://docs.cmsmadesimple.org/&quot; title=&quot;CMS Made Simple Documentation&quot; target=&quot;_blank&quot;&gt;documentation&lt;/a&gt;. If you need any help, the community is always at your service in the  &lt;a class=&quot;external&quot; href=&quot;http://forum.cmsmadesimple.org&quot; title=&quot;CMS Made Simple Forum&quot; target=&quot;_blank&quot;&gt;forum&lt;/a&gt;, and some of them are regularly available at &lt;a class=&quot;external&quot; href=&quot;https://cms-made-simple.slack.com&quot; title=&quot;The CMS Made Simple live-interaction channel&quot; target=&quot;_blank&quot;&gt;Slack&lt;/a&gt;.&lt;/p&gt;&lt;h3&gt;License&lt;/h3&gt;&lt;p&gt;CMS Made Simple is released under the &lt;a class=&quot;external&quot; href=&quot;http://www.gnu.org/licenses/licenses.html#GPL&quot; title=&quot;General Public License&quot; target=&quot;_blank&quot;&gt;GPL&lt;/a&gt; license and as such the site doesn&apos;t have to include a link back to CMSMS, as much as we would welcome such acknowledgement.&lt;/p&gt;&lt;p&gt; Some third party add-on modules may have a different (compatible) license.&lt;/p&gt;]]></content>
		</property>
	</properties>
</cmsmsinstall>
